spring.application.name=library
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/my_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=TRACE
spring.web.error.include-stacktrace=never
jwt.secret=dev-jwt-key-super-secret-123456789
jwt.expiration=3600000
spring.data.web.pageable.default-page-size=10